export enum EstadoPedido {
    CONFIRMAR = 'A CONFIRMAR',
    PENDIENTE = 'PENDIENTE',
    ELABORACION = 'EN ELABORACION',
    LISTO = 'LISTO PARA SERVIR',
    ENTREGADO = 'ENTREGADO',
    CONFIRMADO = 'CONFIRMADO'
}
